### ISSUE TITLE
ESPmDNS not working solution

### ISSUE THREAD

**Issue by krulkip** [witnessmenow/spotify-api-arduino#10]
In the getRefreshToken.ino file
Add following line in declarations
const char* mdnsName = "ESPotify";        // Domain name for the mDNS responder

replace:
  if (MDNS.begin("esp32")) {
    Serial.println("MDNS responder started");
  }
with:
  if (MDNS.begin(mdnsName)) {                        // start the multicast domain name server
  Serial.print("mDNS responder started: http://");
  Serial.print(mdnsName);
  Serial.println(".local");
  }  

And of course change the myDashboard in the spotify for developers page

**Comment by witnessmenow** [comment]
The above doesn't really change anything ,it just moves the string to a different piece of memory.

I have opened a issue with ESP32 to see whats up with it.

https://github.com/espressif/arduino-esp32/issues/5446

**Comment by witnessmenow** [comment]
I think this is a me problem, not related to this library
