### ISSUE TITLE
Add way to get device Ids

### ISSUE THREAD

**Issue by TheNitek** [witnessmenow/spotify-api-arduino#13]
Is there an easy way to get the device ids available in my account? I couldn't find anything on this in the examples/code.

**Comment by witnessmenow** [comment]
There is a Spotify Endpoint for it, but It's not currently supported by this library

https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/

Updated the title of this issue to track this change

**Comment by TheNitek** [comment]
Thanks for the quick response. Sounds like a point to dig into this library and implement it myself :-)

**Comment by witnessmenow** [comment]
Ok cool! Let me know if there is anything I could help with.

I've made a change that takes a step in the direction of implementing this, I created a device Struct.

I think the slightly complicated thing about this is you don't know how many devices will be returned.

**Comment by TheNitek** [comment]
Awesome!

I'm thinking something like this:
`bool getDevices(Device[] devices, uint8_t maxDevices);`
Then the user can decide on how many to expect

**Comment by witnessmenow** [comment]
That's a good solution!

**Comment by witnessmenow** [comment]
I've added this feature to a new branch:

https://github.com/witnessmenow/arduino-spotify-api/tree/GetDeviceIds

Thanks for the PR for it, but I wanted to get the library running more stable before merging it.
