### ISSUE TITLE
I am attempting to get a refresh token in the same project as getting a current song

### ISSUE THREAD

**Issue by Tpow99** [witnessmenow/spotify-api-arduino#18]
This is not an issue, it is more so a question. I have been using(and loving) your API. Individually, both of these examples work great. I am currently trying to use your API to complete both tasks in one project. 

In the setup I first use:

`  WiFiClientSecure client;
ArduinoSpotify spotify(client, clientId, clientSecret);`

To initialize and get refreshtokens, then I use:

`spotify.setRefreshToken(refreshToken);`

To add the refresh token. I have been running into a problem, however, where every time I attempt to use:

`spotify.refreshAccessTokens()` 

I get a no exception wdt reset. When I do not get the wdt reset, the code instead gives me a connection failed response when connecting to spotify. I was wondering if you might now how I could alter the code either in the cpp or my own code to prevent the wdt timeout. Thank you for your help, I love everything you have done on this API so far!

**Comment by witnessmenow** [comment]
I have done some work on a new branch that seems to be more stable on the ESP8266, I need to do some more testing on it though. I did check with the following code on the ESP8266 and seems stable (this code is refreshing the token every time)

```
void loop() {
  if (millis() > requestDueTime)
  {
    Serial.print("Free Heap: ");
    Serial.println(ESP.getFreeHeap());

    Serial.println("Referesh Access token:");
    spotify.refreshAccessToken();
    Serial.println("getting currently playing song:");
    // Market can be excluded if you want e.g. spotify.getCurrentlyPlaying()
    CurrentlyPlaying currentlyPlaying = spotify.getCurrentlyPlaying(SPOTIFY_MARKET);

    printCurrentlyPlayingToSerial(currentlyPlaying);

    requestDueTime = millis() + delayBetweenRequests;
  }

}
```

Try it out and see if its works better for you.

https://github.com/witnessmenow/arduino-spotify-api/tree/CharsToHeap

**Comment by witnessmenow** [comment]
Changes have been moved to the master branch

Closing awaiting more feedback
