### ISSUE TITLE
Create "getRefreshToken" example for WiFi NINA boards (Nano 33 IOT etc)

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/spotify-api-arduino#2]
The library works with WiFiNINA based boards, but there is currently no example to get the refresh token like there is for the ESP8266 or ESP32 based boards. One of those examples would need to be ported to work with the WiFi NINA webserver code.

**Comment by eawystr** [comment]
Hi!

I am testing that, and I get this error:

Attempting to connect to haifisch...
Connected to haifisch
SSID: haifisch
IP Address: 192.168.1.136
signal strength (RSSI):-62 dBm
Refreshing Access Tokens
grant_type=refresh_token&refresh_token=AAAAAAAAAABBBBBBBBBBBCCCCCCCCCCCDDDDDDDDDDD&client_id=f8aeea367669458dac14b17261ff61ea&client_secret=********************************
stack size -536903247
accounts.spotify.com
Status Code: 400
status Code400
getAuthToken error{"error":"invalid_grant","error_description":"Invalid refresh token"}Closing client
Failed to get access tokens
getting currently playing song:
/v1/me/player/currently-playing?market=ES
stack size -536903255
Refresh of the Access token is due, doing that now.
grant_type=refresh_token&refresh_token=AAAAAAAAAABBBBBBBBBBBCCCCCCCCCCCDDDDDDDDDDD&client_id=f8aeea367669458dac14b17261ff61ea&client_secret=********************************
stack size -536902879
accounts.spotify.com
Status Code: 400
status Code400
getAuthToken error{"error":"invalid_grant","error_description":"Invalid refresh token"}Closing client
Status Code: 400
Status Code: 400
stack size -536903255
Closing client

**Comment by witnessmenow** [comment]
Hello

Thanks for taking a look at this.

The part that is missing for WiFi Nina is this part:
https://github.com/witnessmenow/spotify-api-arduino/blob/master/examples/esp8266/getRefreshToken/getRefreshToken.ino

Where the devices hosts a webserver that you use to login into your Spotify account, I think from the serial output it looks like you are using one of the other examples.

I do plan to add a step for this to maybe do this part on PC or something to make it simpler

**Comment by eawystr** [comment]
Sorry but I am too noob to that.

I only wanted to get my currenly playing song on spotify; is that needed?

**Comment by witnessmenow** [comment]
Yeah it is, it's explained a little bit on the readme. 

https://github.com/witnessmenow/spotify-api-arduino#getting-your-refresh-token

The refresh token doesn't need to be got on the Nina style board, but you need to get one

**Comment by eawystr** [comment]
So, it is possible to get the token directly from spotify web?

**Comment by witnessmenow** [comment]
No I don't think so.

**Comment by eawystr** [comment]
Hi!

I managed to get the REFRESH_TOKEN from this web https://alecchendev.medium.com/get-your-spotify-refresh-token-with-this-simple-web-app-d942dad05847

And now, this is the error:

Attempting to connect to SSID: haifisch
Connected to wifi
SSID: haifisch
IP Address: 192.168.1.136
signal strength (RSSI):-60 dBm
Refreshing Access Tokens
grant_type=refresh_token&refresh_token=**********&client_id=**********&client_secret=**********
stack size -536903231
accounts.spotify.com
Connection failed
status Code-1
Could not parse errorFailed to get access tokens
getting currently playing song:
/v1/me/player/currently-playing?market=ES
stack size -536903255
Refresh of the Access token is due, doing that now.
grant_type=refresh_token&refresh_token=**********&client_id=**********&client_secret=**********
stack size -536902879
accounts.spotify.com
Connection failed
status Code-1
Could not parse errorConnection failed
Status Code: -1
stack size -536903255

**Comment by eawystr** [comment]
Maybe my issue now is regarding this:

· _You will also need to add a callback URI for authentication process by clicking "Edit Settings", what URI to add will be mentioned in further instructions_

**Comment by witnessmenow** [comment]
Dropping support for WifiNina boards. In theory they should work, but I will not be supporting them
