### ISSUE TITLE
404 Response with getRefreshToken

### ISSUE THREAD

**Issue by Zurtar** [witnessmenow/spotify-api-arduino#30]
While using the getRefreshToken example for esp8266 Spotify returns the 404 code causing the check serial monitor message to be posted and the serial monitor doesn't give any additional information.

**Comment by witnessmenow** [comment]
What was the issue/fix?

**Comment by Zurtar** [comment]
The example tells you to use the arduino.local address as your callback under the esp8266 examples, I just switched it to esp8266.local and it worked fine
