### ISSUE TITLE
Audio playing

### ISSUE THREAD

**Issue by priyansh-shankhdhar** [witnessmenow/spotify-api-arduino#31]
i am building a project in which i am able able to authorize with spotify and receive token thus getting music information, but i wish to play music and recieve the mp3 audio info ? can we do that ? I yes how?
I am using Esp32

**Comment by witnessmenow** [comment]
Not through the API

Kind of through a project like this, but It's way out of scope for this library:

https://github.com/sle118/squeezelite-esp32
