### ISSUE TITLE
Status: HTTP/1.0 403 Forbidden

### ISSUE THREAD

**Issue by mviher** [witnessmenow/spotify-api-arduino#39]
Hi,
when I try playerControls.ino it does not work, i get Status: HTTP/1.0 403 Forbidden.

Serial monitor:
![Posnetek zaslona 2021-09-05 135325](https://user-images.githubusercontent.com/58395926/132125934-3ade847f-e09e-44d8-a485-faef88ad70c0.png)

but if i try getCurrentlyPlaying.ino, it works.  I tried diferent scopes (user-modify-playback-state and user-read-playback-state) but problem persist.

Is that happening because I don't have premium or is something else?

PS: @witnessmenow Love you work, you are brilliant! <3

**Comment by witnessmenow** [comment]
Hello, Thanks so much!

I believe it is to do with premium ok, similar was reported in #28
