### ISSUE TITLE
Control playback

### ISSUE THREAD

**Issue by Albumlight** [witnessmenow/spotify-api-arduino#42]
Hello Brian,
Very nice library! Deserves support.
Looking at the examples, i.e. playback control.ino. Is it possible to add for example a hardware button to a command?
 
Best,
Rodney

**Comment by cojua8** [comment]
Of course, you can use the "debounce button" example, together with this library and make it work

**Comment by Albumlight** [comment]
Hi cojua8, 

Yes, indeed. Made it work, but had to learn the basics first.
Sorry for posting this as an isssue.

**Comment by Albumlight** [comment]
Supported. Great work !
