### ISSUE TITLE
NoMemory crash for searchForSong() 

### ISSUE THREAD

**Issue by mariusebastian** [witnessmenow/spotify-api-arduino#53]
Is the searchForSong() function tested OK for the esp8266?
When using the Arduino IDE on a NodeMCU clone the getSearchResults example fails with serial output
```
Free Heap: 39104
Making Search Request:
/v1/search
stack size -1073740928
Status: HTTP/1.0 200 OK
HTTP Version: HTTP/1.0
Status Code: 200
Status Code: 200
deserializeJson() failed with code NoMemory
Closing client

```
So is it the negative stack size or the free heap size that's causing the problems?

**Comment by witnessmenow** [comment]
I have never actually used this feature at all! 

From a quick look it looks like the SearchDetailsBufferSize might be too small for your result, might be worth trying bumping that up

`spotify.searchDetailsBufferSize = 3000;` is what it currently is, so you could try increase that.

**Comment by witnessmenow** [comment]
Added some additional info to the example
